# Generated by Django 5.0.1 on 2024-01-07 11:23

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('password', models.CharField()),
                ('birth_day', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon numarsını doğru girin.', regex='^\\+?1?\\d{9,15}$')])),
                ('user_type', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')])),
            ],
        ),
    ]
